# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_pb2 as db__pb2


class DatabaseCommandStub(object):
  """import "google/api/annotations.proto";

  The box database rpc service definition. It's for development only
  get all keys of database
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDatabaseKeys = channel.unary_unary(
        '/rpcpb.DatabaseCommand/GetDatabaseKeys',
        request_serializer=db__pb2.GetDatabaseKeysRequest.SerializeToString,
        response_deserializer=db__pb2.GetDatabaseKeysResponse.FromString,
        )
    self.GetDatabaseValue = channel.unary_unary(
        '/rpcpb.DatabaseCommand/GetDatabaseValue',
        request_serializer=db__pb2.GetDatabaseValueRequest.SerializeToString,
        response_deserializer=db__pb2.GetDatabaseValueResponse.FromString,
        )


class DatabaseCommandServicer(object):
  """import "google/api/annotations.proto";

  The box database rpc service definition. It's for development only
  get all keys of database
  """

  def GetDatabaseKeys(self, request, context):
    """rpc GetDatabaseKeys (GetDatabaseKeysRequest) returns (GetDatabaseKeysResponse) {
    option (google.api.http) = {
    post: "/v1/db/keys"
    body: "*"
    };
    }
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDatabaseValue(self, request, context):
    """get value of associate with passed key in database

    rpc GetDatabaseValue (GetDatabaseValueRequest) returns (GetDatabaseValueResponse) {
    option (google.api.http) = {
    post: "/v1/db/get"
    body: "*"
    };
    }
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatabaseCommandServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDatabaseKeys': grpc.unary_unary_rpc_method_handler(
          servicer.GetDatabaseKeys,
          request_deserializer=db__pb2.GetDatabaseKeysRequest.FromString,
          response_serializer=db__pb2.GetDatabaseKeysResponse.SerializeToString,
      ),
      'GetDatabaseValue': grpc.unary_unary_rpc_method_handler(
          servicer.GetDatabaseValue,
          request_deserializer=db__pb2.GetDatabaseValueRequest.FromString,
          response_serializer=db__pb2.GetDatabaseValueResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rpcpb.DatabaseCommand', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
