# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='rpcpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08\x64\x62.proto\x12\x05rpcpb\"T\n\x16GetDatabaseKeysRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\x0c\n\x04skip\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\"T\n\x17GetDatabaseKeysResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04skip\x18\x03 \x01(\x05\x12\x0c\n\x04keys\x18\x04 \x03(\t\"5\n\x17GetDatabaseValueRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"H\n\x18GetDatabaseValueResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\x32\xb8\x01\n\x0f\x44\x61tabaseCommand\x12P\n\x0fGetDatabaseKeys\x12\x1d.rpcpb.GetDatabaseKeysRequest\x1a\x1e.rpcpb.GetDatabaseKeysResponse\x12S\n\x10GetDatabaseValue\x12\x1e.rpcpb.GetDatabaseValueRequest\x1a\x1f.rpcpb.GetDatabaseValueResponseb\x06proto3')
)




_GETDATABASEKEYSREQUEST = _descriptor.Descriptor(
  name='GetDatabaseKeysRequest',
  full_name='rpcpb.GetDatabaseKeysRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='rpcpb.GetDatabaseKeysRequest.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='rpcpb.GetDatabaseKeysRequest.prefix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip', full_name='rpcpb.GetDatabaseKeysRequest.skip', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='rpcpb.GetDatabaseKeysRequest.limit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=103,
)


_GETDATABASEKEYSRESPONSE = _descriptor.Descriptor(
  name='GetDatabaseKeysResponse',
  full_name='rpcpb.GetDatabaseKeysResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='rpcpb.GetDatabaseKeysResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpcpb.GetDatabaseKeysResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip', full_name='rpcpb.GetDatabaseKeysResponse.skip', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keys', full_name='rpcpb.GetDatabaseKeysResponse.keys', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=189,
)


_GETDATABASEVALUEREQUEST = _descriptor.Descriptor(
  name='GetDatabaseValueRequest',
  full_name='rpcpb.GetDatabaseValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='rpcpb.GetDatabaseValueRequest.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='rpcpb.GetDatabaseValueRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=244,
)


_GETDATABASEVALUERESPONSE = _descriptor.Descriptor(
  name='GetDatabaseValueResponse',
  full_name='rpcpb.GetDatabaseValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='rpcpb.GetDatabaseValueResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpcpb.GetDatabaseValueResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpcpb.GetDatabaseValueResponse.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=318,
)

DESCRIPTOR.message_types_by_name['GetDatabaseKeysRequest'] = _GETDATABASEKEYSREQUEST
DESCRIPTOR.message_types_by_name['GetDatabaseKeysResponse'] = _GETDATABASEKEYSRESPONSE
DESCRIPTOR.message_types_by_name['GetDatabaseValueRequest'] = _GETDATABASEVALUEREQUEST
DESCRIPTOR.message_types_by_name['GetDatabaseValueResponse'] = _GETDATABASEVALUERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDatabaseKeysRequest = _reflection.GeneratedProtocolMessageType('GetDatabaseKeysRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDATABASEKEYSREQUEST,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.GetDatabaseKeysRequest)
  ))
_sym_db.RegisterMessage(GetDatabaseKeysRequest)

GetDatabaseKeysResponse = _reflection.GeneratedProtocolMessageType('GetDatabaseKeysResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDATABASEKEYSRESPONSE,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.GetDatabaseKeysResponse)
  ))
_sym_db.RegisterMessage(GetDatabaseKeysResponse)

GetDatabaseValueRequest = _reflection.GeneratedProtocolMessageType('GetDatabaseValueRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDATABASEVALUEREQUEST,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.GetDatabaseValueRequest)
  ))
_sym_db.RegisterMessage(GetDatabaseValueRequest)

GetDatabaseValueResponse = _reflection.GeneratedProtocolMessageType('GetDatabaseValueResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDATABASEVALUERESPONSE,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:rpcpb.GetDatabaseValueResponse)
  ))
_sym_db.RegisterMessage(GetDatabaseValueResponse)



_DATABASECOMMAND = _descriptor.ServiceDescriptor(
  name='DatabaseCommand',
  full_name='rpcpb.DatabaseCommand',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=321,
  serialized_end=505,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDatabaseKeys',
    full_name='rpcpb.DatabaseCommand.GetDatabaseKeys',
    index=0,
    containing_service=None,
    input_type=_GETDATABASEKEYSREQUEST,
    output_type=_GETDATABASEKEYSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDatabaseValue',
    full_name='rpcpb.DatabaseCommand.GetDatabaseValue',
    index=1,
    containing_service=None,
    input_type=_GETDATABASEVALUEREQUEST,
    output_type=_GETDATABASEVALUERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASECOMMAND)

DESCRIPTOR.services_by_name['DatabaseCommand'] = _DATABASECOMMAND

# @@protoc_insertion_point(module_scope)
